name:                docimp
version:             0.1.0.0
github:              "hugdro/docimp"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "None."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/whatsupfudd/docimp#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  - containers
  - unordered-containers
  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  - unix
  # For Cont(T):
  - mtl
  # For UUID:
  - uuid
  # For HTTP:
  - http-client
  - http-client-tls
  - http-types
  # For SQL:
  - postgresql-binary
  - hasql
  - hasql-th
  - hasql-pool
  - hasql-transaction
  - profunctors
  # For scientific:
  - scientific
  # For pandoc:
  - pandoc >= 3.1
  - pandoc-types
  - megaparsec
  - hashable
  - cryptonite
  - memory
  - base16-bytestring
  - aeson
  - aeson-pretty
  - zip-archive
  - xml-conduit
  # For oai to .docx gen:
  - data-default
  # For HTML scraping:
  - scalpel


default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot

ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  docimp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docimp

tests:
  docimp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docimp
